(()=>{
"use strict";
const API="https://web2apk.traderwithsbt.workers.dev", $=id=>document.getElementById(id);
function preview(input,img){input.addEventListener("change",()=>{const f=input.files?.[0];if(!f)return;if(!f.type.startsWith("image/")){alert("Please select an image.");input.value="";return}if(f.size>10*1024*1024){alert("Image must be 10 MB or smaller.");input.value="";return}img.src=URL.createObjectURL(f);img.style.display="block"})}
preview($("icon"),$("iconPreview"));preview($("splash"),$("splashPreview"));
$("themeBtn").onclick=()=>{document.body.classList.toggle("dark");$("themeBtn").textContent=document.body.classList.contains("dark")?"☀":"☾"};
function packageFromName(n){let v=String(n||"app").toLowerCase().replace(/[^a-z0-9]+/g,"").slice(0,18);if(!v||!/^[a-z]/.test(v))v="app";return "com.web2apk."+v}
$("appName").oninput=e=>{if(!$("packageName").dataset.edited){$("packageName").value=packageFromName(e.target.value);$("splashTitle").value=e.target.value}}
$("packageName").oninput=()=>$("packageName").dataset.edited="1";
function setProgress(n,t){n=Math.max(0,Math.min(100,n));$("bar").style.width=n+"%";$("percent").textContent=n+"%";$("statusText").textContent=t}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]))}
function blob(file,kind){return new Promise((res,rej)=>{const r=new FileReader();r.onerror=()=>rej(new Error("Could not read image."));r.onload=()=>{const im=new Image();im.onerror=()=>rej(new Error("Could not decode image."));im.onload=()=>{const max=kind==="icon"?512:1080,mh=kind==="icon"?512:1920;let w=im.width,h=im.height;if(kind==="icon"){const side=Math.min(w,h),sx=(w-side)/2,sy=(h-side)/2;w=h=side;const sc=Math.min(1,max/side),c=document.createElement("canvas");c.width=c.height=Math.max(1,Math.round(side*sc));c.getContext("2d").drawImage(im,sx,sy,side,side,0,0,c.width,c.height);c.toBlob(x=>x?res(x):rej(new Error("Image compression failed.")),"image/webp",.86)}else{const sc=Math.min(1,max/w,mh/h),c=document.createElement("canvas");c.width=Math.max(1,Math.round(w*sc));c.height=Math.max(1,Math.round(h*sc));c.getContext("2d").drawImage(im,0,0,c.width,c.height);c.toBlob(x=>x?res(x):rej(new Error("Image compression failed.")),"image/webp",.86)}};im.src=r.result};r.readAsDataURL(file)})}
async function poll(id){const r=await fetch(API+"/status/"+encodeURIComponent(id),{cache:"no-store"}),j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||"Status check failed");setProgress(j.progress||0,j.status==="complete"?"APK ready!":j.status==="error"?"Build failed":j.status==="queued"?"Waiting for GitHub Actions…":"Building your APK…");$("logs").textContent=(j.logs||[]).join("\n");if(j.status==="complete"){$("result").classList.remove("hidden");$("result").innerHTML="<b>✅ APK generated successfully</b><br>Download your customized Android app below.<br><a target='_blank' rel='noopener' href='"+esc(j.downloadUrl)+"'>Download APK</a>";$("buildBtn").disabled=false;return}if(j.status==="error"){$("result").classList.remove("hidden");$("result").innerHTML="<b>❌ Build failed</b><br>"+esc(j.error||"Unknown error");$("buildBtn").disabled=false;return}setTimeout(()=>poll(id).catch(showError),2000)}
function showError(e){setProgress(0,"Build failed");$("logs").textContent+=("\n"+(e.message||e));$("result").classList.remove("hidden");$("result").innerHTML="<b>❌ Error</b><br>"+esc(e.message||e);$("buildBtn").disabled=false}
$("buildBtn").onclick=async()=>{const url=$("url").value.trim(),name=$("appName").value.trim()||"My Website App";if(!/^https?:\/\/.+/i.test(url)){alert("Please enter a valid http/https website URL.");return}const fd=new FormData();const add=(k,v)=>fd.append(k,String(v));add("url",url);add("appName",name);add("packageName",$("packageName").value.trim()||packageFromName(name));add("versionName",$("versionName").value.trim()||"1.0");add("versionCode",$("versionCode").value.trim()||"1");
["orientation","splashBgType","splashBg","splashBg2","splashText","splashAccent","splashAlign","splashLoading","splashAnimation","splashMs","splashTitle","splashTagline"].forEach(id=>add(id,$(id).value));
["splashEnabled","splashShowLogo","splashShowTitle","splashShowTagline","splashShowLoading","backNavigation","exitConfirm","internetCheck","fileUpload","fileDownload","pullToRefresh","externalLinks","zoomEnabled","keepScreenOn","preventScreenshots","cameraPermission","microphonePermission","locationPermission"].forEach(id=>add(id,$(id).checked));
try{if($("icon").files[0]){setProgress(1,"Preparing app icon…");fd.append("icon",await blob($("icon").files[0],"icon"),"icon.webp")}if($("splash").files[0]){setProgress(2,"Preparing splash logo…");fd.append("splash",await blob($("splash").files[0],"splash"),"splash.webp")}}catch(e){showError(e);return}
$("buildBtn").disabled=true;$("progressWrap").classList.remove("hidden");$("result").classList.add("hidden");$("logs").textContent="";setProgress(5,"Sending build request…");try{const r=await fetch(API+"/build",{method:"POST",body:fd}),j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||"Build request failed");await poll(j.jobId)}catch(e){showError(e)}};
})();
